# Generated by Django 5.2.13 on 2026-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('special', models.BooleanField(default=False)),
            ],
        ),
    ]
